/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright(c) 2021 Intel Corporation.
 */
#if !defined(RH79_COMPAT_H)
#define RH79_COMPAT_H

#define HAVE_NEW_UVERBS_ASYNC_EVENT_FILE
#ifndef HAVE_MOFED
#define CREATE_AH_HAS_UDATA
#define HAVE_IB_GID_ATTR
#define POST_HAS_CONST
#define CREATE_FLOW_HAS_UDATA
#define HAVE_ALLOC_RDMA_NETDEV
#define HAVE_RDMA_NETDEV_GET_PARAMS
#define UVERBS_FILE_NO_DISASSOCIATE_PAGE
#undef	CONFIG_EVENT_TRACING
#define IDR_REMOVE_NO_RETURN
#define NO_GET_RANDOM_U32
#else
#define HAVE_ENUM_IB_UVERBS_ADVISE_MR_ADVICE
#define HAVE_FALLTHROUGH
#define HAVE_IB_DEVICE_OPS
#define UVERBS_DEVICE_NO_EVENTS_FILE_LIST
#define UVERBS_FILE_NO_EVENT_HANDLER
#define UVERBS_FILE_HAS_DEFAULT_ASYNC_FILE
#define UVERBS_FILE_HAVE_XARRAY_IDR
#define UVERBS_FILE_NO_IDR_LOCK
#define RDMA_LOOKUP_GET_UOBJECT_HAVE_ATTR
#define TYPE_CLASS_NO_NEEDS_KFREE_RCU
#define IB_CLIENT_ADD_RETURN_INT
#define NO_RB_ROOT_CACHE
#define IB_UMEM_GET_WITH_UDATA
#define DEREG_MR_HAS_UDATA
#endif

#include "compat_common.h"

#endif /* RH79_COMPAT_H */
