/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright(c) 2021 Intel Corporation.
 */
#if !defined(RH84_COMPAT_H)
#define RH84_COMPAT_H

#define HAVE_FALLTHROUGH
#define CREATE_AH_HAS_INIT_ATTR
#define HAVE_ALLOC_RDMA_NETDEV
#define CREATE_FLOW_HAS_UDATA
#define HAVE_IB_GID_ATTR
#define HAVE_RDMA_NETDEV_GET_PARAMS
#define HAVE_ENUM_IB_UVERBS_ADVISE_MR_ADVICE
#define HAVE_IB_DEVICE_OPS
#define POST_HAS_CONST
#define DESTROY_AH_RETURNS_VOID
#define DEALLOC_PD_HAS_UDATA
#define DESTROY_CQ_HAS_UDATA
#define DESTROY_QP_HAS_UDATA
#define DEREG_MR_HAS_UDATA
#define HAVE_MMU_NOTIFIER_RANGE
#define UVERBS_DEVICE_NO_EVENTS_FILE_LIST
#define HAVE_NEW_UVERBS_ASYNC_EVENT_FILE
#define UVERBS_FILE_NO_EVENT_HANDLER
#define UVERBS_FILE_HAS_DEFAULT_ASYNC_FILE
#define UVERBS_FILE_HAVE_XARRAY_IDR
#define UVERBS_FILE_NO_IDR_LOCK
#define RDMA_LOOKUP_GET_UOBJECT_HAVE_ATTR
#define HAVE_ATOMIC_FETCH_ADD_UNLESS
#define TYPE_CLASS_NO_NEEDS_KFREE_RCU
#define HAVE_XARRAY
#define IB_CLIENT_ADD_RETURN_INT
#define IB_UMEM_GET_WITH_UDATA

#include "compat_common.h"

#endif /* RH84_COMPAT_H */
